### ISSUE TITLE
Blocks that didn't convert.  

### ISSUE THREAD

**Issue by Bel26** [Conquest-Reforged/WorldConverter#1]
I converted one of my Builds on Rekt's server and I made a list of blocks that didn't convert.  

Light blue wool
Red Clay
Acacia Beam
Horizontal Carved Spruce Wall
Marble base Column med
Smooth Marble column.  
Tan Sandstone
Red Sand

**Comment by HIPPOKLEIDES** [comment]
Was it just the full blocks that didn't convert or certain variants/shapes (ie: wall, vertical slab, etc)?

If there were variants that didn't convert, could you list those as well?

**Comment by Bel26** [comment]
Horizontal carved Spruce wall and the Marble base column were the only to variants that didn't convert.  The rest were full blocks

**Comment by HIPPOKLEIDES** [comment]
I've made some fixes to the converter and have run a few tests successfully converting these blocks.
