### ISSUE TITLE
Blocks that didn’t Convert and Some Other Issues

### ISSUE THREAD

**Issue by Comeondownsweet** [Conquest-Reforged/WorldConverter#2]
Some issues I found when converting my world.

Blocks that don’t convert to anything | Recommended   New Variant
-- | --
~~Dark Ornament Blocks~~ | ~~Stripped Dark Oak Wood Beam~~
~~Stone 1:0~~ | ~~Limestone~~
~~Brick X Frame~~ | ~~Brick X Frame~~
~~Dark Sandstone~~ | ~~Small Brown Sandstone Brick~~
~~Elven Pillar 2~~ | ~~Fancy Elvin Pillar Design~~
~~White Plaster Design~~ | ~~White Stucco Design~~
~~Pillar Quartz Block~~ | ~~Marble Column~~
~~Bronze Lattice Small Pillar~~ | ~~Bronze Lattice Pane~~
~~Elvin Wave Pillar~~ | ~~Simple Elvin Column Design~~
~~Red Tiles~~ | ~~Magenta Concrete (its variations are   called Red Painted Angled Tile)~~
~~Marble Base Slab~~ | ~~Marble Plinth 1 Slab~~
~~Marble Cornice Block Slab~~ | ~~Marble Plinth Slab (There doesn’t   seem to be the old Marble Cornice Slab)~~
~~Old Podzol~~ | ~~Autumnal Forest Floor~~
~~Mossy Oak Log Pillar~~ | ~~Mossy Oak Log Branch Vertical~~
~~Mossy Spruce Log Pillar~~ | ~~Mossy Dark Spruce Log Branch Vertical~~
~~Dark Broad Leaves~~ | ~~Dark Broad Leaves~~
~~Pink Roof tiles Corner Block~~ | ~~Pink Clay Tile Vertical Corner (Layer   3)~~
~~Red Sandstone Base Column Pillar~~ | ~~Red Column With Sandstone Base Wall~~
~~Horizontal Carved Spruce Wood   Small Pillar~~ | ~~Carved Spruce Wood Pillar (There doesn’t   seem to be pillar versions of old design)~~
~~Gray Ivory Pillar Trapdoor~~ | ~~Carved Ash Wood Pillar~~
~~Ruined Stone Brick Corner Block~~ | ~~Weather Limestone Brick Vertical   Corner (Layer 3)~~
~~Skeleton Skull~~ | ~~Skeleton Skull~~
~~Newel Capped Wood Fence~~ | ~~Newel Capped Oak Wood Fence~~
~~Nailed Oak Planks (and its   variants)~~ | ~~Rustic Spruce Wood Planks~~
~~Sandstone Base Column~~ | ~~Sandstone Column With Sandstone   Base~~
~~Iron Fence Small Pillar~~ | ~~Wrought Iron Fence Pane~~

**Blocks that were replaced incorrectly**

What they were | What   they are now | What   they should be
-- | -- | --
~~Wooden Shutters~~ | ~~Gone~~ | ~~Simple Oak Wooden Shutters~~
~~Limestone Big Slab &   Variations~~ | ~~Light Clay Tiles~~ | ~~Large Limestone Block~~
~~White Ivory Pillar ~~| ~~Polychrome Architrave~~ | ~~Fancy Elvin Marble Column~~
~~Oak Woods Planks Trapdoor~~ | ~~Ashwood Plank Slab~~| ~~Oak Wood Plank Slab~~
~~Overgrown Podzol~~ | ~~Muddy Autumnal Forest Floor~~ | ~~Mossy Soil~~
~~Chiselled Quartz Trapdoor~~ | ~~Elven Marble Base Vertical Slab~~ | ~~Chiselled Polished Parian Marble   Design Vertical Slab~~
~~Brown-Gray Wood Shingles (and   Variations)~~ | ~~Brown Wood Shingles~~ | ~~Brown-Gray Wood Shingles~~

Other Issues
| -- |
~~Coloured and Oak Shutters spawn in   water blocks~~
~~Oak doors are in wrong position but   right block~~
~~Horizontal beams often aren’t in   the right alignment~~
~~The new Slabs are 4 layers when   they should be 3~~
~~Window Panes no longer connect   vertical corners~~
~~Wall blocks don’t seem to connect~~
~~Empty Racks seem to be inverted~~
~~Wheels don’t seem to work~~

Let me know if you need more info.

**Comment by domusan** [comment]
blocks are gone after conversion from 1.12: all column bases, fancy elven pillar design, simple elven column design, bronze lattice pane, white stucco design

**Comment by domusan** [comment]
plinth marble blocks all waterlogged after conversion

**Comment by HIPPOKLEIDES** [comment]
Should be resolved in next version
