### ISSUE TITLE
Converter removing Light Blue Wool-Blocks

### ISSUE THREAD

**Issue by Moredir** [Conquest-Reforged/WorldConverter#4]
All 'Light Blue Wool-Blocks got removed, when converting from 1.12.2 to 1.15.
Used the WorldConverter-2.0.0 version.
Before Conversion:
![2021-06-13_11 30 36](https://user-images.githubusercontent.com/85825065/121802054-de9e0700-cc3a-11eb-8841-23b6da00c2ce.png)

After conversion:
![2021-06-13_11 30 01](https://user-images.githubusercontent.com/85825065/121802041-cded9100-cc3a-11eb-9abf-05e6b836c6dd.png)

**Comment by HIPPOKLEIDES** [comment]
Looks like it was a little typo. Should be fixed for the next release
